spring:
  profiles:
    active:
    - dev
  application:
    name: '@project.name@'
    
build:
  version: '@project.version@'
  timestamp: '@timestamp@'
    
logging:
  pattern:
    console: '[%-8(%X{LOG_TYPE})] %d{yyyy-MM-dd HH:mm:ss} [${spring.application.name},${build.version},${spring.profiles}] [%M\(%F:%L\)] : %msg%n'